name: Build Windows Installers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: false
        default: '1.0.0'
        type: string

jobs:
  build-windows-exe:
    name: Build Windows .exe with jpackage
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build Fat JAR
        run: ./gradlew shadowJar
      
      - name: Create Windows .exe with jpackage
        run: |
          jpackage `
            --input build/libs `
            --name "EZLedger" `
            --main-jar "EZLedger-1.0.0-all.jar" `
            --main-class "MainKt" `
            --type exe `
            --dest dist `
            --app-version "${{ github.event.inputs.version || '1.0.0' }}" `
            --description "EZLedger - Secure Financial Management" `
            --vendor "YOTTA Systems" `
            --copyright "© 2024 YOTTA Systems" `
            --win-dir-chooser `
            --win-menu `
            --win-shortcut
      
      - name: Upload Windows .exe
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*.exe
          retention-days: 30
  
  build-legacy-installers:
    name: Build Legacy Installers (Docker-based)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build with Gradle
        run: ./gradlew buildSecureJar
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Build Secure Windows Distribution
        run: |
          chmod +x ./build-secure-windows.sh
          ./build-secure-windows.sh
      
      - name: Upload NSIS Installer
        uses: actions/upload-artifact@v4
        with:
          name: nsis-installer
          path: installer-dist/*.exe
          retention-days: 30
      
      - name: Upload Portable Distribution
        uses: actions/upload-artifact@v4
        with:
          name: portable-distribution
          path: |
            secure-dist/EZLedger-Secure-Windows.zip
            secure-dist/EZLedger-Secure-Windows.tar.gz
          retention-days: 30